DROP TRIGGER IF EXISTS JETX_TEMPLATE_UPDATE_TRIGGER;
DROP TRIGGER IF EXISTS JETX_TEMPLATE_INSERT_TRIGGER;
DROP TABLE IF EXISTS JETX_TEMPLATE;

CREATE TABLE JETX_TEMPLATE (
	NAME  varchar(255) NOT NULL,
	LAST_MODIFIED timestamp NOT NULL,
	CONTENT  text NOT NULL,
	PRIMARY KEY (NAME)
) ENGINE=InnoDB;


DELIMITER |
CREATE TRIGGER JETX_TEMPLATE_UPDATE_TRIGGER BEFORE UPDATE ON JETX_TEMPLATE 
	FOR EACH ROW BEGIN
		SET NEW.LAST_MODIFIED = NOW();
	END
|
DELIMITER ;


DELIMITER |
CREATE TRIGGER JETX_TEMPLATE_INSERT_TRIGGER BEFORE INSERT ON JETX_TEMPLATE 
	FOR EACH ROW BEGIN
		SET NEW.LAST_MODIFIED = NOW();
	END
|
DELIMITER ;